// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP2cm6OWXVRKw7ga4zQ76ydI4Evanhhhg',
    appId: '1:764499744432:web:f7755b539f67a8c7cd4d75',
    messagingSenderId: '764499744432',
    projectId: 'quality-control-project',
    authDomain: 'quality-control-project.firebaseapp.com',
    storageBucket: 'quality-control-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSBBQZZNbiGquDfbWqLcwyKdzfYeRn9AE',
    appId: '1:764499744432:android:708971e05e30ecfbcd4d75',
    messagingSenderId: '764499744432',
    projectId: 'quality-control-project',
    storageBucket: 'quality-control-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNbJcdJeHwYs3qmOwxrTMRciA0NxvIAC0',
    appId: '1:764499744432:ios:96381a76673d8670cd4d75',
    messagingSenderId: '764499744432',
    projectId: 'quality-control-project',
    storageBucket: 'quality-control-project.appspot.com',
    iosBundleId: 'com.example.flutterEgitim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNbJcdJeHwYs3qmOwxrTMRciA0NxvIAC0',
    appId: '1:764499744432:ios:96381a76673d8670cd4d75',
    messagingSenderId: '764499744432',
    projectId: 'quality-control-project',
    storageBucket: 'quality-control-project.appspot.com',
    iosBundleId: 'com.example.flutterEgitim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP2cm6OWXVRKw7ga4zQ76ydI4Evanhhhg',
    appId: '1:764499744432:web:655373bd656836fdcd4d75',
    messagingSenderId: '764499744432',
    projectId: 'quality-control-project',
    authDomain: 'quality-control-project.firebaseapp.com',
    storageBucket: 'quality-control-project.appspot.com',
  );
}
